version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing dependencies...
      - npm install

  build:
    commands:
      - echo Building Next.js static site...
      - npm run build:static

  post_build:
    commands:
      - echo Deploying to S3...
      - aws s3 sync out/ s3://finextlabs.com --delete
      - echo Invalidating CloudFront cache...
      - aws cloudfront create-invalidation --distribution-id E2NAU7CCWEDA6J --paths "/*"

artifacts:
  files:
    - '**/*'
